name = "FlatMigi"
license = "MIT"
description = "A minimalist monospace theme inspired by ericmigi.com."
authors = ["EuphoricPenguin]
homepage = "https://github.com/EuphoricPenguin/FlatMigi"

[module]
  [[module.imports]]
    path = "github.com/gohugoio/hugo-mod-jslibs-dist/popperjs/v2"
    disable = false

[min_version]
  hugo = "0.113.0"